# 应用名称
server:
  port: 8888

spring:
  profiles:
    active: git
  application:
    name: cloud-config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    config:
      label: master
      discovery:
        enabled: true
      server:
        git:
          uri: http://192.168.12.134/jiuha/fancy-cloud-config.git
          search-paths: '{application}'
          username: funny
          password: 19970407
        accept-empty: false
        default-label: master
      profile: dev
    #Spring Bus配置自动刷新配置
    bus:
      refresh:
        enabled: true
      id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
    #Spring stream配置
    stream:
      kafka:
        binder:
          brokers:
            - 192.168.12.140:9092
  kafka:
    bootstrap-servers:
      - 192.168.12.140:9092
    consumer:
      group-id: config-client

logging:
  level:
    org.springframework.cloud.bus: debug


